action:
- service: fan.turn_on
  target:
    entity_id: fan.bathroom_fan
alias: Turn on the bathroom fan when the humidity is above 60%
condition:
- condition: state
  entity_id: fan.bathroom_fan
  state: 'off'
trigger:
  above: 60
  entity_id: sensor.bathroom_humidity
  platform: numeric_state
