action:
- data:
    message: The washing machine has finished.
  service: notify.notify
alias: Send a notification when the washing machine finishes
condition:
- condition: state
  entity_id: input_boolean.washing_machine_notification
  state: 'on'
trigger:
  entity_id: sensor.washing_machine_power
  platform: state
  to: 'off'
