action:
- service: light.turn_off
  target:
    entity_id: light.hallway
alias: Turn off the hallway lights when no motion is detected for 10 minutes
trigger:
  entity_id: binary_sensor.hallway_motion
  for:
    minutes: 10
  platform: state
  to: 'off'
