action:
- service: light.turn_on
  target:
    entity_id: light.living_room
alias: Turn on the living room lights when motion is detected and the lights are off
condition:
- condition: state
  entity_id: light.living_room
  state: 'off'
trigger:
  entity_id: binary_sensor.living_room_motion
  platform: state
  to: 'on'
