action:
- service: light.turn_on
  target:
    entity_id: light.kitchen
alias: Turn on the kitchen lights when motion is detected
condition:
  after: sunset
  before: sunrise
  condition: sun
trigger:
  entity_id: binary_sensor.kitchen_motion
  platform: state
  to: 'on'
