action:
- service: media_player.turn_off
  target:
    entity_id: media_player.tv
alias: Turn off the TV when no motion is detected in the living room for 30 minutes
condition:
- condition: state
  entity_id: media_player.tv
  state: 'on'
trigger:
  entity_id: binary_sensor.living_room_motion
  for:
    minutes: 30
  platform: state
  to: 'off'
