action:
- service: light.turn_on
  target:
    entity_id: light.bedroom
alias: Turn on the bedroom lights when motion is detected
condition:
  after: sunset
  before: sunrise
  condition: sun
trigger:
  entity_id: binary_sensor.bedroom_motion
  platform: state
  to: 'on'
