action:
- data:
    message: Front door is open
  service: notify.notify
alias: Send a notification when the front door is opened
trigger:
  entity_id: binary_sensor.front_door
  platform: state
  to: 'on'
