action:
- service: light.turn_on
  target:
    entity_id: light.hallway
alias: Turn on lights when motion is detected in the hallway
condition:
  condition: state
  entity_id: sun.sun
  state: below_horizon
trigger:
  entity_id: binary_sensor.hallway_motion
  platform: state
  to: 'on'
