action:
- service: light.turn_off
  target:
    entity_id: light.porch
alias: Turn off the porch light when the front door is locked
trigger:
  entity_id: lock.front_door
  platform: state
  to: locked
