action:
- data:
    message: The garage door has been open for more than 10 minutes.
  service: notify.notify
alias: Send a notification when the garage door is left open for more than 10 minutes
trigger:
  entity_id: binary_sensor.garage_door
  for:
    minutes: 10
  platform: state
  to: 'on'
