action:
- service: light.turn_off
  target:
    entity_id: light.garage
alias: Turn off the garage lights when the garage door is closed
trigger:
  entity_id: cover.garage_door
  platform: state
  to: closed
