action:
- service: fan.turn_off
  target:
    entity_id: fan.bathroom_fan
alias: Turn off the bathroom fan when the humidity is below 50%
condition:
- condition: state
  entity_id: fan.bathroom_fan
  state: 'on'
trigger:
  below: 50
  entity_id: sensor.bathroom_humidity
  platform: numeric_state
