action:
- service: light.turn_on
  target:
    entity_id: light.bathroom
alias: Turn on the bathroom lights when motion is detected
condition:
  after: sunset
  before: sunrise
  condition: sun
trigger:
  entity_id: binary_sensor.bathroom_motion
  platform: state
  to: 'on'
