action:
- service: light.turn_on
  target:
    entity_id: light.porch
alias: Turn on the porch light when the front door is unlocked
trigger:
  entity_id: lock.front_door
  platform: state
  to: unlocked
