action:
- service: light.turn_off
  target:
    entity_id: light.bedroom
alias: Turn off the bedroom lights when no motion is detected for 10 minutes
trigger:
  entity_id: binary_sensor.bedroom_motion
  for:
    minutes: 10
  platform: state
  to: 'off'
