action:
- service: light.turn_on
  target:
    entity_id: light.bedroom
alias: Turn on the bedroom lights when the alarm goes off
condition:
- condition: state
  entity_id: light.bedroom
  state: 'off'
trigger:
  entity_id: alarm_control_panel.home_alarm
  platform: state
  to: triggered
