action:
- service: light.turn_off
  target:
    entity_id: group.hallway_lights
alias: Turn off the hallway lights when the front door is closed
trigger:
  entity_id: binary_sensor.front_door
  platform: state
  to: 'off'
