action:
- service: light.turn_on
  target:
    entity_id: light.porch
alias: Turn on the porch light when the front door is unlocked
condition:
  after: sunset
  before: sunrise
  condition: sun
trigger:
  entity_id: lock.front_door
  platform: state
  to: unlocked
