action:
- data:
    message: The refrigerator door has been left open for more than 5 minutes.
  service: notify.notify
alias: Notify when the refrigerator door is left open for more than 5 minutes
trigger:
  entity_id: binary_sensor.refrigerator_door
  for:
    minutes: 5
  platform: state
  to: 'on'
