action:
- service: switch.turn_on
  target:
    entity_id: switch.coffee_machine
alias: Turn on the coffee machine when the first person wakes up
condition:
  after: 06:00:00
  before: '10:00:00'
  condition: time
trigger:
  entity_id: group.family
  from: asleep
  platform: state
  to: home
