action:
- service: light.turn_on
  target:
    entity_id: group.living_room_lights
alias: Turn on the living room lights when motion is detected
condition:
  after: sunset
  before: sunrise
  condition: sun
trigger:
  entity_id: binary_sensor.living_room_motion
  platform: state
  to: 'on'
