action:
- service: switch.turn_on
  target:
    entity_id: switch.coffee_machine
alias: Turn on the coffee machine when the alarm goes off in the morning
condition:
  after: 06:00:00
  before: 09:00:00
  condition: time
trigger:
  entity_id: alarm_control_panel.home_alarm
  platform: state
  to: triggered
