action:
- service: light.turn_off
  target:
    entity_id: light.hallway
alias: Turn off the hallway light after 3 minutes of no motion
condition:
- condition: state
  entity_id: light.hallway
  state: 'on'
trigger:
  entity_id: binary_sensor.hallway_motion
  for:
    minutes: 3
  platform: state
  to: 'off'
