action:
- service: light.turn_on
  target:
    entity_id: light.hallway
alias: Turn on the hallway light when the front door is opened during nighttime
condition:
- condition: state
  entity_id: sun.sun
  state: below_horizon
trigger:
  entity_id: binary_sensor.front_door
  platform: state
  to: 'on'
