action:
- data:
    message: The front door has been opened.
  service: notify.notify
alias: Send a notification when the front door is opened
trigger:
  entity_id: binary_sensor.front_door
  platform: state
  to: 'on'
