action:
- service: light.turn_off
  target:
    entity_id: light.bathroom
alias: Turn off the bathroom lights when no motion is detected for 5 minutes
trigger:
  entity_id: binary_sensor.bathroom_motion
  for:
    minutes: 5
  platform: state
  to: 'off'
